"""The paper and the pipeline cannot drift apart: every number macro the manuscript uses must be
generated by `python -m mbca study paper`, and every generated table/figure it inputs must exist."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "paper"
SOURCES = [ROOT / "MBCA_paper.tex", *sorted((ROOT / "sections").glob("*.tex"))]


def _text(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def test_every_number_macro_is_generated():
    defined = set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", _text(ROOT / "tex" / "numbers.tex")))
    used = set()
    for f in [*SOURCES, *(ROOT / "tex").glob("s2_*.tex")]:
        used |= set(re.findall(r"\\(S(?:one|Two|qrt)[A-Za-z]+)", _text(f)))
    assert used, "no macros found"
    assert not (used - defined), f"undefined result macros: {sorted(used - defined)}"


def test_every_input_and_figure_exists():
    for f in SOURCES:
        for inc in re.findall(r"\\input\{([^}]+)\}", _text(f)):
            assert (ROOT / inc).exists(), f"{f.name}: missing \\input {inc}"
        for fig in re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", _text(f)):
            assert (ROOT / fig).exists(), f"{f.name}: missing figure {fig}"


def test_results_sections_contain_no_hand_typed_decimals():
    """Result sections may contain decimals only inside generated macros (e.g. no '+0.37' typed by hand)."""
    for name in ("04_study1.tex", "06_study2_results.tex", "09_conclusion.tex", "01_intro.tex"):
        body = _text(ROOT / "sections" / name)
        body = re.sub(r"\\(?:input|includegraphics|label|ref|cite[pt]?)(?:\[[^\]]*\])?\{[^}]*\}", "", body)
        typed = re.findall(r"(?<![\d.])[+-]?\d+\.\d+", body)
        assert not typed, f"{name}: hand-typed numbers {typed[:5]}"
