"""Generate every number, table and figure the paper uses. Nothing is typed by hand.

    python -m mbca study paper

Writes:
    paper/tex/numbers.tex     \\newcommand macros for every in-text number (Study 1 + Study 2)
    paper/tex/s1_*.tex        Study 1 tables      paper/tex/s2_*.tex   Study 2 tables
    paper/figures/s1_*.png    Study 1 figures     paper/figures/s2_*.png Study 2 figures
Macro names use letters only (pandoc's LaTeX reader expands plain \\newcommand macros).
"""
from __future__ import annotations

import re

import numpy as np
import pandas as pd

from .config import ROOT, load_config

PAPER = ROOT / "paper"
TEX, FIG = PAPER / "tex", PAPER / "figures"
AN = ROOT / "results" / "study2" / "analysis"
S1 = ROOT / "results"

STRAT = {"jma_trend": "JMA", "sma_cross": "SMA", "donchian": "Donchian", "ts_momentum": "TSMOM", "rsi_reversion": "RSI",
         "rsi2_reversion": "RSI"}
STRAT_LABEL = {"jma_trend": "JMA crossover", "sma_cross": "SMA 50/200-type crossover", "donchian": "Donchian breakout",
               "ts_momentum": "Time-series momentum", "rsi2_reversion": "RSI(2) reversion"}
COMP = {"rule_adx": "Adx", "regime_linearity": "Regime", "meta_label": "Meta", "position_sizing": "Sizing",
        "entry": "Entry", "exit": "Exit", "best_combined": "Best"}
COMP_LABEL = {"rule_adx": "Rule ADX gate", "regime_linearity": "ML regime filter", "meta_label": "ML meta-labeling",
              "position_sizing": "ML position sizing", "entry": "ML entry", "exit": "ML exit",
              "best_combined": "Meta-label + sizing"}
FRZ = {"F2008": "A", "F2018": "B"}
MKT_LABEL = {"equity_indices": "Equity indices", "equity_etfs": "Equity ETFs", "fixed_income": "Fixed income",
             "commodities": "Commodities", "fx": "FX", "crypto": "Crypto", "stocks_us": "US stocks",
             "stocks_intl": "Intl stocks", "ALL": "All markets"}


class Macros:
    def __init__(self):
        self.d: dict[str, str] = {}

    def __setitem__(self, name, value):
        assert re.fullmatch(r"[A-Za-z]+", name), name
        self.d[name] = value

    def write(self, path):
        lines = ["% GENERATED by `python -m mbca study paper` -- do not edit"]
        lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.d.items())]
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def f2(x, signed=False):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{x:+.2f}" if signed else f"{x:.2f}"


def pct(x, signed=False):
    return f"{100 * x:+.1f}\\%" if signed else f"{100 * x:.1f}\\%"


def esc(s):
    return str(s).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&").replace("^", "\\^{}")


def longtable(path, caption, label, header, rows, align):
    out = [f"\\begin{{longtable}}{{{align}}}",
           f"\\caption{{{caption}}} \\label{{{label}}} \\\\", "\\toprule", " & ".join(header) + " \\\\",
           "\\midrule", "\\endhead", "\\bottomrule", "\\endfoot"]
    out += [" & ".join(map(str, r)) + " \\\\" for r in rows]
    out.append("\\end{longtable}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


# =========================================================================== Study 1
S1_KIND = {"ML Regime Filter": "independent", "ML Meta-Labeling": "narrowing", "ML Position Sizing": "narrowing",
           "ML Entry": "replacing", "ML Exit": "replacing", "Combinations": "combination"}


def study1(M: Macros) -> None:
    from .report import forest_plot, matrix_plot

    p = pd.read_csv(S1 / "paper" / "component_attribution_table.csv")
    rep = pd.read_csv(S1 / "replication" / "attribution_table.csv")
    cmp_ = pd.read_csv(S1 / "replication" / "paper_vs_replication.csv")
    M["SoneConfigs"] = str(len(p))
    M["SoneSigGain"] = str(int((p.significant & (p.delta_sharpe > 0)).sum()))
    M["SoneSigLoss"] = str(int((p.significant & (p.delta_sharpe < 0)).sum()))
    ex = p[p.component == "ML Exit"]
    M["SoneExitSigLoss"] = str(int((ex.significant & (ex.delta_sharpe < 0)).sum()))
    M["SoneExitConfigs"] = str(len(ex))
    # trade-count inflation of ML Exit vs its campaign baseline (paper CSV)
    e = pd.read_csv(S1 / "paper" / "ml_exit_all.csv")
    r = (e[e.variant == "ml_exit"].set_index(["market", "window"])["n_trades"]
         / e[e.variant == "baseline"].set_index(["market", "window"])["n_trades"]).dropna()
    M["SoneExitInflLo"], M["SoneExitInflHi"] = f"{r.min():.1f}", f"{r.max():.1f}"
    bc = p[(p.component == "Combinations") & p.variant.str.startswith("Best") & (p.market == "indian_equities")]
    for w, tag in (("holdout", "Hold"), ("forward", "Fwd")):
        row = bc[bc.window == w].iloc[0]
        M[f"SoneBest{tag}Base"], M[f"SoneBest{tag}Var"] = f2(row.baseline_sharpe), f2(row.variant_sharpe)
        M[f"SoneBest{tag}CiLo"], M[f"SoneBest{tag}CiHi"] = f"{row.bootstrap_ci_lo:.3f}", f"{row.bootstrap_ci_hi:.3f}"
        M[f"SoneBest{tag}CiLoAnn"] = f"{row.bootstrap_ci_lo * np.sqrt(252):.1f}"
        M[f"SoneBest{tag}CiHiAnn"] = f"{row.bootstrap_ci_hi * np.sqrt(252):.1f}"
    fxb = p[(p.market == "forex_4pair") & (p.window == "holdout")].baseline_sharpe.iloc[0]
    M["SoneForexBase"] = f2(fxb)
    fx = p[p.market == "forex_4pair"]
    M["SoneForexSigLoss"], M["SoneForexConfigs"] = str(int((fx.significant & (fx.delta_sharpe < 0)).sum())), str(len(fx))
    # replication
    M["SoneRepSigGain"] = str(int((rep.significant & (rep.delta_sharpe > 0) & (rep.kind != "control")).sum()))
    M["SoneRepSigLoss"] = str(int((rep.significant & (rep.delta_sharpe < 0)).sum()))
    M["SoneRepSignAgree"] = str(int(cmp_.sign_agrees.sum()))
    fxr = cmp_[cmp_.market == "forex"]
    M["SoneRepForexSigLoss"] = str(int((fxr.significant_rep & (fxr.delta_sharpe_rep < 0)).sum()))
    ml = rep[rep.variant == "ML Exit"].set_index(["market", "window"])["n_trades"]
    bl = rep[rep.variant == "Baseline (rule-based)"].set_index(["market", "window"])["n_trades"]
    rr = (ml / bl).dropna()
    M["SoneRepExitInflLo"], M["SoneRepExitInflHi"] = f"{rr.min():.1f}", f"{rr.max():.1f}"
    b = cmp_[(cmp_.market == "indian_equities") & cmp_.variant.str.startswith("Best")].set_index("window")
    M["SoneRepBestHold"], M["SoneRepBestFwd"] = f2(b.loc["holdout", "delta_sharpe_rep"], True), f2(
        b.loc["forward", "delta_sharpe_rep"], True)
    M["SoneBestHoldDelta"], M["SoneBestFwdDelta"] = f2(b.loc["holdout", "delta_sharpe_paper"], True), f2(
        b.loc["forward", "delta_sharpe_paper"], True)
    rb = rep[(rep.variant == "Baseline (rule-based)")].set_index(["market", "window"])["sharpe"]
    M["SoneRepForexBase"] = f2(rb.loc[("forex", "holdout")])
    M["SoneRepIndiaBase"] = f2(rb.loc[("indian_equities", "holdout")])
    mf = cmp_[(cmp_.market == "forex") & (cmp_.variant == "ML Meta-Labeling")].iloc[0]
    M["SoneMetaForexPaper"], M["SoneMetaForexRep"] = f2(mf.delta_sharpe_paper, True), f2(mf.delta_sharpe_rep, True)

    # tables
    rows = [[esc(r.component), esc(r.variant), esc(r.market), r.window, f2(r.baseline_sharpe), f2(r.variant_sharpe),
             f2(r.delta_sharpe, True), f"[{r.bootstrap_ci_lo:.3f}, {r.bootstrap_ci_hi:.3f}]",
             "\\textbf{yes}" if r.significant else "no"] for r in p.itertuples()]
    longtable(TEX / "s1_attribution.tex", "Study 1: all 60 configurations (original study results). CI = unpaired "
              "i.i.d.\\ bootstrap of the per-day Sharpe difference.", "tab:s1", ["Component", "Variant", "Market",
              "Window", "Base", "Variant", "$\\Delta$SR", "95\\% CI (per day)", "Sig."], rows, "l l l l r r r l l")
    rows = [[esc(r.market), r.window, esc(r.variant), f2(r.delta_sharpe_paper, True), f2(r.delta_sharpe_rep, True),
             "sig." if r.significant_paper else "n.s.", "sig." if r.significant_rep else "n.s."] for r in cmp_.itertuples()]
    longtable(TEX / "s1_replication.tex", "Study 1: original results vs.\\ independent re-implementation "
              "(annualized $\\Delta$Sharpe).", "tab:s1rep", ["Market", "Window", "Variant", "Original", "Replication",
              "Orig.", "Repl."], rows, "l l l r r l l")
    # figures (unit-corrected)
    t = p.rename(columns={"variant_sharpe": "sharpe", "bootstrap_ci_lo": "ci_lo", "bootstrap_ci_hi": "ci_hi"})
    t["kind"] = t["component"].map(S1_KIND)
    t["variant"] = [v if c in ("ML Regime Filter", "Combinations") else c for c, v in zip(t.component, t.variant)]
    forest_plot(t, FIG / "s1_forest.png", "Study 1: delta Sharpe vs rule-based baseline")
    matrix_plot(t, FIG / "s1_matrix.png", "Study 1: ML Opportunity Matrix")


# =========================================================================== Study 2
def build() -> None:
    TEX.mkdir(exist_ok=True)
    FIG.mkdir(exist_ok=True)
    M = Macros()
    study1(M)
    if (AN / "tests.csv").exists():
        from .paper_study2 import study2
        study2(M)
    M.write(TEX / "numbers.tex")
    print(f"wrote {len(M.d)} macros to {TEX / 'numbers.tex'}")
